/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusRouteImport } from './routes/bus'
import { Route as ControlRouteImport } from './routes/control'
import { Route as HealthRouteImport } from './routes/health'
import { Route as MiniRouteImport } from './routes/mini'
import { Route as NoopRouteImport } from './routes/noop'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as ApiCountriesRouteImport } from './routes/api.countries'
import { Route as ApiDatasetsRouteImport } from './routes/api.datasets'
import { Route as ApiStateRouteImport } from './routes/api.state'
import { Route as ApiTimeRouteImport } from './routes/api.time'
import { Route as ApiWorldRouteImport } from './routes/api.world'
import { Route as ApiControlAuthRouteImport } from './routes/api.control.auth'
import { Route as ApiDatasetsIdRouteImport } from './routes/api.datasets.$id'
import { Route as ApiMiniInviteRouteImport } from './routes/api.mini.invite'
import { Route as ApiMiniSessionRouteImport } from './routes/api.mini.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRoute = BusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniRoute = MiniRouteImport.update({
  id: '/mini',
  path: '/mini',
  getParentRoute: () => rootRouteImport,
} as any)
const NoopRoute = NoopRouteImport.update({
  id: '/noop',
  path: '/noop',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesRoute = ApiCountriesRouteImport.update({
  id: '/api/countries',
  path: '/api/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetsRoute = ApiDatasetsRouteImport.update({
  id: '/api/datasets',
  path: '/api/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimeRoute = ApiTimeRouteImport.update({
  id: '/api/time',
  path: '/api/time',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorldRoute = ApiWorldRouteImport.update({
  id: '/api/world',
  path: '/api/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlAuthRoute = ApiControlAuthRouteImport.update({
  id: '/api/control/auth',
  path: '/api/control/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatasetsIdRoute = ApiDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDatasetsRoute,
} as any)
const ApiMiniInviteRoute = ApiMiniInviteRouteImport.update({
  id: '/api/mini/invite',
  path: '/api/mini/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMiniSessionRoute = ApiMiniSessionRouteImport.update({
  id: '/api/mini/session',
  path: '/api/mini/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/control': typeof ControlRoute
  '/health': typeof HealthRoute
  '/mini': typeof MiniRoute
  '/noop': typeof NoopRoute
  '/screen': typeof ScreenRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/api/state': typeof ApiStateRoute
  '/api/time': typeof ApiTimeRoute
  '/api/world': typeof ApiWorldRoute
  '/api/control/auth': typeof ApiControlAuthRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/mini/invite': typeof ApiMiniInviteRoute
  '/api/mini/session': typeof ApiMiniSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/control': typeof ControlRoute
  '/health': typeof HealthRoute
  '/mini': typeof MiniRoute
  '/noop': typeof NoopRoute
  '/screen': typeof ScreenRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/api/state': typeof ApiStateRoute
  '/api/time': typeof ApiTimeRoute
  '/api/world': typeof ApiWorldRoute
  '/api/control/auth': typeof ApiControlAuthRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/mini/invite': typeof ApiMiniInviteRoute
  '/api/mini/session': typeof ApiMiniSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bus': typeof BusRoute
  '/control': typeof ControlRoute
  '/health': typeof HealthRoute
  '/mini': typeof MiniRoute
  '/noop': typeof NoopRoute
  '/screen': typeof ScreenRoute
  '/api/countries': typeof ApiCountriesRoute
  '/api/datasets': typeof ApiDatasetsRouteWithChildren
  '/api/state': typeof ApiStateRoute
  '/api/time': typeof ApiTimeRoute
  '/api/world': typeof ApiWorldRoute
  '/api/control/auth': typeof ApiControlAuthRoute
  '/api/datasets/$id': typeof ApiDatasetsIdRoute
  '/api/mini/invite': typeof ApiMiniInviteRoute
  '/api/mini/session': typeof ApiMiniSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus'
    | '/control'
    | '/health'
    | '/mini'
    | '/noop'
    | '/screen'
    | '/api/countries'
    | '/api/datasets'
    | '/api/state'
    | '/api/time'
    | '/api/world'
    | '/api/control/auth'
    | '/api/datasets/$id'
    | '/api/mini/invite'
    | '/api/mini/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus'
    | '/control'
    | '/health'
    | '/mini'
    | '/noop'
    | '/screen'
    | '/api/countries'
    | '/api/datasets'
    | '/api/state'
    | '/api/time'
    | '/api/world'
    | '/api/control/auth'
    | '/api/datasets/$id'
    | '/api/mini/invite'
    | '/api/mini/session'
  id:
    | '__root__'
    | '/'
    | '/bus'
    | '/control'
    | '/health'
    | '/mini'
    | '/noop'
    | '/screen'
    | '/api/countries'
    | '/api/datasets'
    | '/api/state'
    | '/api/time'
    | '/api/world'
    | '/api/control/auth'
    | '/api/datasets/$id'
    | '/api/mini/invite'
    | '/api/mini/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusRoute: typeof BusRoute
  ControlRoute: typeof ControlRoute
  HealthRoute: typeof HealthRoute
  MiniRoute: typeof MiniRoute
  NoopRoute: typeof NoopRoute
  ScreenRoute: typeof ScreenRoute
  ApiCountriesRoute: typeof ApiCountriesRoute
  ApiDatasetsRoute: typeof ApiDatasetsRouteWithChildren
  ApiStateRoute: typeof ApiStateRoute
  ApiTimeRoute: typeof ApiTimeRoute
  ApiWorldRoute: typeof ApiWorldRoute
  ApiControlAuthRoute: typeof ApiControlAuthRoute
  ApiMiniInviteRoute: typeof ApiMiniInviteRoute
  ApiMiniSessionRoute: typeof ApiMiniSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus': {
      id: '/bus'
      path: '/bus'
      fullPath: '/bus'
      preLoaderRoute: typeof BusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini': {
      id: '/mini'
      path: '/mini'
      fullPath: '/mini'
      preLoaderRoute: typeof MiniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noop': {
      id: '/noop'
      path: '/noop'
      fullPath: '/noop'
      preLoaderRoute: typeof NoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries': {
      id: '/api/countries'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasets': {
      id: '/api/datasets'
      path: '/api/datasets'
      fullPath: '/api/datasets'
      preLoaderRoute: typeof ApiDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/time': {
      id: '/api/time'
      path: '/api/time'
      fullPath: '/api/time'
      preLoaderRoute: typeof ApiTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/world': {
      id: '/api/world'
      path: '/api/world'
      fullPath: '/api/world'
      preLoaderRoute: typeof ApiWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control/auth': {
      id: '/api/control/auth'
      path: '/api/control/auth'
      fullPath: '/api/control/auth'
      preLoaderRoute: typeof ApiControlAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/datasets/$id': {
      id: '/api/datasets/$id'
      path: '/$id'
      fullPath: '/api/datasets/$id'
      preLoaderRoute: typeof ApiDatasetsIdRouteImport
      parentRoute: typeof ApiDatasetsRoute
    }
    '/api/mini/invite': {
      id: '/api/mini/invite'
      path: '/api/mini/invite'
      fullPath: '/api/mini/invite'
      preLoaderRoute: typeof ApiMiniInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mini/session': {
      id: '/api/mini/session'
      path: '/api/mini/session'
      fullPath: '/api/mini/session'
      preLoaderRoute: typeof ApiMiniSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDatasetsRouteChildren {
  ApiDatasetsIdRoute: typeof ApiDatasetsIdRoute
}

const ApiDatasetsRouteChildren: ApiDatasetsRouteChildren = {
  ApiDatasetsIdRoute: ApiDatasetsIdRoute,
}

const ApiDatasetsRouteWithChildren = ApiDatasetsRoute._addFileChildren(
  ApiDatasetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusRoute: BusRoute,
  ControlRoute: ControlRoute,
  HealthRoute: HealthRoute,
  MiniRoute: MiniRoute,
  NoopRoute: NoopRoute,
  ScreenRoute: ScreenRoute,
  ApiCountriesRoute: ApiCountriesRoute,
  ApiDatasetsRoute: ApiDatasetsRouteWithChildren,
  ApiStateRoute: ApiStateRoute,
  ApiTimeRoute: ApiTimeRoute,
  ApiWorldRoute: ApiWorldRoute,
  ApiControlAuthRoute: ApiControlAuthRoute,
  ApiMiniInviteRoute: ApiMiniInviteRoute,
  ApiMiniSessionRoute: ApiMiniSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
